### ISSUE TITLE
width and height of Scroll pHAT HD should rotate

### ISSUE THREAD

**Issue by dglaude** [pimoroni/scroll-phat-hd#16]
The idea is that portable code (that use width and height) would work even if there is a rotation in place.

Even if discussed here and aggreed it would be a better choice, I am not sure I want to write the pull request for this as there is more than one way to do it with various impact depending on where to put the abstraction for that.

This code:
```
#!/usr/bin/env python

import scrollphathd as sphd

print(sphd.width)
print(sphd.height)
sphd.rotate(90)
print(sphd.width)
print(sphd.height)

```

This should display:
```
17
7
7
17

```

**Comment by Gadgetoid** [comment]
This has pretty far reaching impact deep within the guts of the library; the width/height properties are involved with drawing pixels directly to the display memory.

It also has some interesting side-effects, since the display buffer is not rotated, but is rotated before its displayed. So if you:

```
scrollphathd.fill(0, 0, scrollphathd.width, scrollphathd.height)
scrollphathd.rotate(90)
scrollphathd.fill(0, 0, scrollphathd.width, scrollphathd.height)
```

You would end up with a buffer containing something like this:

```
[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]
[][][][][][][]
[][][][][][][]
[][][][][][][]
[][][][][][][]
[][][][][][][]
[][][][][][][]
[][][][][][][]
[][][][][][][]
[][][][][][][]
[][][][][][][]
```

Whereas what you were probably going for was:

```
[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]
[][][][][][][][][][][][][][][][][]
```

IE: All drawing operations are still performed as if the display is not rotated, and rotate is only performed before the buffer is displayed: https://github.com/pimoroni/scroll-phat-hd/blob/master/library/scrollphathd/is31fl3731.py#L307-L357

Show does all the heavy lifting:

* Takes a copy of the buffer
* Scrolls the copied buffer using `numpy.roll` along the X and Y axis in turn
* Rotates the copied buffer using `numpy.rot90`
* Flips the copied buffer along the Y axis
* Flips the copied buffer along the X axis
* Creates a list of 144 zeros
* Iterates through the display size of `self.width` * `self.height` and grabs the appropriate pixel from the copied buffer into the output list.
* Splits the output list into 32byte chunks and sends it to the display over i2c

This is so you can prep an arbitrary sized buffer full of text and then scroll/rotate/flip etc to your hearts content without having to redraw anything manually.

**Comment by dglaude** [comment]
I know this is a farfetching idea with deep impact... That's why I will not
do it myself. :-)

In Unicorn pHAT we have get_shape() that is rotation aware and rotation
exist in 0, 90, 180 and 270.
In Scroll pHAT don't even get width and height and the rotation is only at
0 and 180 (like Unicorn pHAT in the past).

One option would be to use get_shape in the 3 library.
Then you could rename width into _width and height into _height across
Scroll pHAT HD library to indicate it is private.

So far, width and height are not documented ( http://docs.pimoroni.com/
scrollphathd/ ) nor explained ( https://learn.pimoroni.com/
tutorial/sandyj/getting-started-with-scroll-phat-hd ) nor seems to be used
in example ( https://github.com/pimoroni/scroll-phat-hd/tree/master/examples
).

This seems like you have a licence to change things for a better.

It would make sense to have the same mechanism between Scroll pHAT and
Scroll pHAT HD as to reuse example where possible.
It would make sense to have the same mechanism between Scroll pHAT HD and
Unicorn too.


2017-03-22 11:24 GMT+01:00 Philip Howard <notifications@github.com>:

**Comment by ali1234** [comment]
Renamed it to get_shape to match the other library.
