### ISSUE TITLE
"curl -sS https://get.pimoroni.com/scrollphathd | bash" retrieves old library version

### ISSUE THREAD

**Issue by TheDiveO** [pimoroni/scroll-phat-hd#20]
When using "curl -sS https://get.pimoroni.com/scrollphathd | bash" on a fresh install, it retrieves an old version of the scrollphathd library which lacks, for instance, the `set_brightness()` method. Unfortunately, the new version in this github repository is still named as `0.0.1` in the module definition. Which gives?

**Comment by RogueM** [comment]
yes - that is by design... that is the only combination of library and examples that is considered compatible, I know in this instance it's not.

Regardless, the repo is 'development' and not considered stable resources - hence why it is not yet tagged as 0.0.2 - and the installers will always use the latest release (from raspbian at-repo or pypi if it does not exist there, and a snapshot of the examples at that same point in history).

If you want the latest code then you should git clone this repo and manually install the library using setuptools, keeping in mind that while it may include improvements and fixes it may be broken in other ways.

**Comment by TheDiveO** [comment]
Thank you very much for this clarification! I've already cloned the Pimoroni repository locally and installed from this using pip.
