### ISSUE TITLE
Support inverse text

### ISSUE THREAD

**Issue by TheDiveO** [pimoroni/scroll-phat-hd#24]
At the moment, the function for drawing characters supports only white pixels on black background: it sets all pixels in the character bounding box. As it is, this makes it impossible to draw inverse chars with dark pixels against a white background. It would be useful to also allow inverse chars.

**Comment by Gadgetoid** [comment]
Regarding #25;

I think this is a good start, but I'm not sure it would fully satisfy the challenge of inverse text since it doesn't set the background colour of the gaps between letters.

I've tested an alternate approach which involves drawing in the background fill manually and then drawing text on top with a brightness of 0. This *almost* works out of the box, but requires a small tweak to `draw_char` to avoid filling any black pixels.

I'd consider this tweak a bugfix, because previously if you drew white text over a white background it would "punch" the characters out of the background, leaving the background colour between letters  which might be a desirable effect to some but definitely feels wrong.

Anyway I've added this tweak into the devel branch, plus an "inverse-text.py" example. See:

https://github.com/pimoroni/scroll-phat-hd/commit/42f7a49948626a15a2efcfe685f4cdc09021a289

**Comment by TheDiveO** [comment]
That fix would be already sufficient for my use cases, as I'm drawing an outer box manually. I wasn't sure that fixing the background painting would break existing code, but an optional parameter would allow for fixed functionality without breaking old code.

From my perspective, this would satisfy me needs, so the pull could be nixed.

**Comment by dglaude** [comment]
Reading your comment, I feel that an on/off behaviour will not work well
with dithered font that are not made only of 0x00 and 0xFF.
Maybe just like there is flipx, flipy and rotate, there could be a global
brightness inversion?

2017-04-03 16:11 GMT+02:00 TheDiveO <notifications@github.com>:

**Comment by TheDiveO** [comment]
For the reason of dithered fonts I wrote my patch suggestion that way to interpolate between the particular pixel brightness (regardless of glyph "foreground" or "background") and the assumed background brightness.

**Comment by Gadgetoid** [comment]
I'll leave this issue open for further discussion, but for now I consider it fixed in v1.0.0, pending perhaps some refinements down the line.
