### ISSUE TITLE
Port samples from Scroll pHAT repo

### ISSUE THREAD

**Issue by Kisty** [pimoroni/scroll-phat-hd#39]
I've ported the `local-weather.py` sample from the scroll pHAT repo. Been meaning to do a pull request but would it be worth porting all of them? It's the only sample that I know of that's missing. Are there any others?

**Comment by Kisty** [comment]
There's quite a few examples missing

Scroll pHAT HD | Scroll pHAT
----------------- | ------------
https://github.com/pimoroni/scroll-phat/tree/master/examples | https://github.com/pimoroni/scroll-phat-hd/tree/master/examples

**Comment by Gadgetoid** [comment]
I've put out for a wider call for help on this one- not because I need it, but because I think it would present a valuable learning opportunity to others if they took up the mantle and tried porting an example.

### @everyone
* To avoid the duplication of effort; should you start porting another example, please let us know here.
* Please tackle only one example at a time and submit only one example in a PR at any one time. (it's easier to feedback) - unless they're *really* closely related.
* If you think we're missing something and you'd like to write a new example instead, that'd be wonderful!

**Comment by Kisty** [comment]
Ok, so I have already ported `local_weather.py` just need to push it.

**Comment by Kisty** [comment]
Hmm, so the file is ona backup of an sd card using `dd` and can't mount the disk image unfortunately. Do u have any ideas how to get it off? I could jist restore the backup to the card.

**Comment by dglaude** [comment]
I ported all the example from Scroll pHAT to Scroll pHAT HD with a single adaptation layer #43 
It is not optimal in handeling the brightness, and it is a one to one mapping, so many pixels of the Scroll pHAT HD are not used. Best result could be archieved by replacing text scrolling call from one library to the other, there the better resolution will be fully used.

@Kisty One option is to put your image on a USB key, boot a Rasbperry Pi and then loopmount the image file. Maybe following this kind of instruction https://github.com/mozilla-iot/wiki/wiki/Loop-mounting-a-Raspberry-Pi-image-file-under-linux or google loop mounting rasberry pi image

**Comment by Gadgetoid** [comment]
I've closed that PR for now, since:
1. I was unable to get it to w ork
2. It'd be nicer and more useful to people trying to learn by example if they were direct ports
